//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAuto0KmWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoConcesionaria
    {
        public int ID_Concesionaria_Vehiculo { get; set; }
        public int Vehiculo_Id { get; set; }
        public int Concesionaria_Id { get; set; }
        public decimal PrecioFinanciadoDolares { get; set; }
        public int MaximoPlazoFinanciacion { get; set; }
        public int MinimoPlazoFinanciacion { get; set; }
        public decimal PrecioListaDolares { get; set; }
        public decimal EntregaDolares { get; set; }
    
        public virtual Concesionaria Concesionaria { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
