//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAuto0Km
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auto()
        {
            this.AutoConcesionarias = new HashSet<AutoConcesionaria>();
        }
    
        public int ID_Auto { get; set; }
        public string Descripcion { get; set; }
        public int TipoAuto_Id { get; set; }
        public int Marca_Id { get; set; }
        public double Motor { get; set; }
        public int Modelo { get; set; }
        public int TipoTransmision_Id { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual TipoAuto TipoAuto { get; set; }
        public virtual TipoTransmision TipoTransmision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoConcesionaria> AutoConcesionarias { get; set; }
    }
}
