//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAuto0Km
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        public int ID_Marca { get; set; }
        public string Nombre_Marca { get; set; }
        public string Descripcion_Marca { get; set; }
    }
}
