//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAuto0Km
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Marca
    {
        [JsonProperty(PropertyName = "IdMarca")]
        public int ID_Marca { get; set; }
        [JsonProperty(PropertyName = "Nombre")]
        public string Nombre_Marca { get; set; }
        [JsonProperty(PropertyName = "Descripcion")]
        public string Descripcion_Marca { get; set; }
    }
}
