//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAuto0Km
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAuto
    {
        [JsonProperty(PropertyName = "Id")]
        public int ID_Tipo_Auto { get; set; }
        [JsonProperty(PropertyName = "Descripcion")]
        public string Descripion { get; set; }
    }
}
