//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiAuto0Km
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.VehiculoConcesionarias = new HashSet<VehiculoConcesionaria>();
        }
    
        public int ID_Auto { get; set; }
        public string Descripcion { get; set; }
        public int Tipo_Auto_Id { get; set; }
        public int TipoTransmision_id { get; set; }
        public int Marca_Id { get; set; }
        public decimal MotorCC { get; set; }
        public string Modelo { get; set; }
        public int Anho { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual TipoAuto TipoAuto { get; set; }
        public virtual TipoTransmision TipoTransmision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculoConcesionaria> VehiculoConcesionarias { get; set; }
    }
}
